// Service worker: offline shell + cache-busting.
//
// THE ONE RULE: bump V whenever you change a precached SHELL file. A new V is what refreshes the
// shell — forget the bump and your fix ships to the repo but never to anyone's installed
// home-screen copy (iOS caches the SW aggressively). scripts/sw-lint.py guards this, and app.js
// surfaces a "tap to update" tag so a stuck phone is fixable in one tap.
//
// Strategy, by what the file IS rather than where it lives:
//   HTML/JS + navigations → network-first (a push is visible on the next reload without waiting
//     for a SW swap; offline falls back to cache and ALWAYS ends at a real Response)
//   JSON → paint from cache now. PRECACHED json is owned by the install, so a V bump is what
//     refreshes it; any other same-origin json is stale-while-revalidate
//   images and everything else → cache-first for speed; a V bump is what refreshes them
//   cross-origin data (your APIs) → straight through, never cached here
//
// The precache is PER-FILE — deliberately never a bare cache.addAll(). That buys self-healing and
// costs a third cache state, PARTIAL, which this whole file then has to reason about. Three
// questions addAll answered implicitly become live, and every function below answers one of them:
//   1. is this version's cache COMPLETE?     → ensureShell() / topUpThenCollect()
//   2. which GENERATION answers a read?      → cacheLookup(), the directional collect
//   3. is a complete-looking cache BOOTABLE? → bootable() / offlineFallback()
// Get one wrong and the failure is a blank white screen offline, a lost offline copy, or a stale
// one that never updates. The seven review rounds behind this design: #7.

const V = "app-v7";   // <-- BUMP ON EVERY SHELL CHANGE (rename the stem freely; keep the digits)

// "app-v" — the stem shared by every cache generation. app.js's VER_PREFIX must match it, and the
// NUMERIC TAIL is load-bearing: it orders generations for the collect below and for checkVer()'s
// ranking in app.js. scripts/sw-lint.py rejects a V without digits at commit time.
const V_STEM = V.replace(/\d+$/, "");

// Numeric generation of a cache name, or null if it isn't one of ours. Used to make the collect
// directional: a worker may only delete caches OLDER than its own.
function verNum(name) {
  const tail = name.startsWith(V_STEM) ? name.slice(V_STEM.length) : "";
  return /^\d+$/.test(tail) ? parseInt(tail, 10) : null;
}

const SHELL = [
  "./", "./index.html", "./styles.css",
  "./app.js", "./theme.js", "./data.js", "./pullToRefresh.js", "./ping.js", "./manifest.json",
  "./assets/icon.svg", "./assets/icon-180.png", "./assets/icon-192.png", "./assets/icon-512.png",
  "./usage/", "./usage/index.html", "./usage/crunch.js",
  // ...add every file the app needs offline: more pages, data JSON, self-hosted fonts.
];

// Absolute hrefs of the SHELL, resolved once so cachePut()'s ownership check is a Set lookup and
// not a URL parse per request. self.location is the sw.js URL, so "./" resolves to the scope root.
// MUST stay below the SHELL declaration — a const read from its own TDZ throws at script
// evaluation, which kills the whole worker: no install, no precache, blank screen offline.
const SHELL_HREFS = new Set(SHELL.map(u => new URL(u, self.location).href));

// Which SHELL entries this version's cache is missing. No network — pure cache reads.
//
// One parallel batch rather than an await per entry: app.js pings "ensure-shell" on every load,
// every controllerchange, and every foreground, and each ping runs this TWICE (the top-up, then
// the re-check in topUpThenCollect). Serialized, that's dozens of sequential Cache API round
// trips every time an iOS home-screen app foregrounds with a complete shell and nothing to do.
async function missingFromShell(cache) {
  const c = cache || await caches.open(V);
  const found = await Promise.all(SHELL.map(url => c.match(url)));
  return SHELL.filter((_, i) => !found[i]);
}

// Precache top-up. Deliberately NOT cache.addAll(): addAll is atomic, so a single 404 (a shell
// file renamed and the list not updated, a file deleted during scaffolding, icons not yet
// generated by make-icons.sh, a mid-deploy blip) rejects the whole install and the device ends up
// with NO cache at all — offline then shows a blank screen. Per-file puts degrade instead:
// whatever fetched is cached, the rest retries.
//
// It also only fetches what's MISSING, which makes it safe to call repeatedly — that's how an
// evicted cache repairs itself. iOS reclaims script-writable storage (Cache API included) under
// pressure and after ~7 idle days, and can leave the cache NAME behind while dropping the
// contents. install only runs on a V bump, so without this top-up a once-evicted cache stays
// empty forever and the app is permanently blank offline.
//
// Returns { transient, permanent }: HOW MANY entries failed in a way a retry could fix, and WHICH
// entries failed in a way no retry ever will. topUpThenCollect() keys the old-cache collect off
// that split, so both have to mean "not cached", not "attempted".
//
// Why the split: the collect waits for a complete precache, so a SHELL entry that can never be
// fetched — a renamed file, a typo'd path — would otherwise keep it waiting FOREVER. Both cache
// generations then live on the device permanently, with the old one still answering (via
// cacheLookup's whole-store fallback) for anything absent from the new one. A 404 is a bug in the
// SHELL list that no amount of retrying repairs, so it must not hold the collect hostage;
// everything genuinely retryable still does. scripts/sw-lint.py catches the repo-side version of
// this at commit time, before it can ship — this path is damage control, not the guard.
//
// Deliberately CONSERVATIVE about what counts as permanent, because guessing wrong trades a
// working offline copy for an empty one. A REDIRECT is transient — a captive portal redirects
// everything, and that is a mobile-normal state, not a broken shell list. 5xx is transient (a
// mid-deploy blip). 408/429 are transient by definition. A 206 is transient — a partial means the
// file IS on the server and some hop answered a plain GET with a range. Only a definite "this URL
// is not on the server" — 4xx other than those — is permanent.
//
// KNOWN LIMITATION: a put() that fails for QUOTA is counted transient, which keeps the old cache
// and so keeps consuming the quota that just ran out. Harmless at this skeleton's shell size, but
// CLAUDE.md §Offline tells adopters to precache PDFs and media — exactly where the shell gets big
// enough for this to bite. A larger shell should evict the old version to make room instead of
// holding both.
async function ensureShellOnce() {
  try {
    const c = await caches.open(V);
    const missing = await missingFromShell(c);
    const outcome = await Promise.all(missing.map(url =>
      fetch(url, { cache: "reload" })
        .then(resp => {
          // A redirected response can't satisfy a navigation (the SW spec rejects it), and
          // resp.ok is TRUE for a 206 but put() then throws. Skip both rather than poison the
          // entry. Every SHELL entry is same-origin, so there's no opaque case to exempt here —
          // unlike cachePut(), which the Google Fonts branch feeds cross-origin no-cors responses.
          if (resp.redirected || resp.status === 206) return "transient";
          if (!resp.ok) {
            return resp.status >= 500 || resp.status === 408 || resp.status === 429
              ? "transient" : "permanent";
          }
          return c.put(url, resp).then(() => "ok", () => "transient");
        })
        .catch(() => "transient")   // offline: leave it for the next attempt
    ));
    return {
      transient: outcome.filter(r => r === "transient").length,
      permanent: missing.filter((_, i) => outcome[i] === "permanent"),
    };
  } catch {
    // CacheStorage itself is unavailable — site data blocked, storage corrupt. Transient by
    // definition, and reporting the whole shell as retryable keeps the old cache as the net.
    return { transient: SHELL.length, permanent: [] };
  }
}

// install, activate, and the "ensure-shell" message can all fire close together; without this a
// V bump would fetch the whole shell 2-3x on a cellular connection. Callers that arrive mid-run
// join it instead of starting their own.
let shellRun = null;
function ensureShell() {
  return shellRun ??= ensureShellOnce().finally(() => { shellRun = null; });
}

self.addEventListener("install", e => {
  e.waitUntil(ensureShell().then(() => self.skipWaiting()));
});

// REPAIR BEFORE COLLECT, and only collect once THIS version's cache is complete.
//
// addAll's atomicity was a liability (one 404 lost the whole precache) but it was also a guard:
// a failed install meant the new SW never activated, so the previous cache kept serving. Per-file
// puts removed that guard — install now always resolves — so collecting first would let a V bump
// on a dead connection trade a working stale offline copy for an empty new one.
//
// "Complete" here means EVERY FETCHABLE SHELL URL IS PRESENT. It also means they came from the
// SAME deploy, because cachePut() refuses to write SHELL urls (see the note there): each
// generation's shell is fetched once, by the install that created it, so the net this keeps is
// coherent rather than merely complete by entry count.
//
// Keeping the old cache is NOT free, which is why this has to be re-runnable rather than a
// one-shot in activate: CacheStorage.match() iterates caches in CREATION order, so while an old
// version lingers it ANSWERS FIRST and shadows the current shell (verified in both engines —
// caches ['app-v6','app-v7'] both holding a URL resolve to the v6 copy). A lingering old cache
// means the device serves the previous release offline, and checkVer() reads the wrong installed
// version. cacheLookup() closes the read-path shadowing by construction, but the storage cost and
// the checkVer() confusion persist until something collects — and activate fires once per SW
// version, hence the retry from the message handler below, the only hook that runs after
// activation.
async function topUpThenCollect() {
  const { transient, permanent } = await ensureShell();
  if (transient > 0) return transient;              // keep the old cache as a net, try again later

  try {
    // Re-verify rather than trusting that count. ensureShell() dedupes concurrent callers, so a
    // joiner receives a completeness reading taken BEFORE it joined — if eviction landed mid-run,
    // "complete" is already false and we'd collect the net out from under a broken shell. Cheap
    // (cache reads only) and it makes the collect depend on current state, not a stale promise.
    //
    // Entries this run proved PERMANENTLY unfetchable are excluded: they are missing by definition
    // and always will be, so counting them here would re-wedge the collect that the transient/
    // permanent split exists to unwedge.
    const recheck = (await missingFromShell()).filter(u => !permanent.includes(u)).length;
    if (recheck > 0) return recheck;

    // Don't collect while another version is mid-install. From this worker's perspective the
    // incoming release's cache is merely "not V", so deleting it would throw away a precache that
    // is being built right now — and app.js pings us on load, which is exactly when an update
    // installs. Whichever worker activates next runs this same step and collects then.
    const reg = self.registration;
    if (reg && (reg.installing || reg.waiting)) return 0;

    // ...but that guard alone is NOT enough, so the collect is also DIRECTIONAL: only strictly
    // OLDER generations, never "everything that isn't me". An incoming worker calls skipWaiting()
    // as soon as its install resolves, at which point it is `active` with installing and waiting
    // both null — so an outgoing worker still finishing a slow top-up sails past the guard above
    // and deletes the new version's freshly built precache (observed downstream: the incoming
    // cache stuck at 7-9 of 13 entries while the old complete one survived, deleted mid-fill).
    // Comparing generations makes that impossible from either side regardless of who runs when.
    //
    // Caches that aren't ours (verNum → null) are left alone rather than swept: this worker has
    // no claim on them, and "delete everything unfamiliar" is how a SW eats a sibling app's
    // storage on a shared origin. V MUST END IN DIGITS: without a numeric tail verNum(V) is null,
    // `n < null` is false for every cache, and collection silently stops — no error, no symptom,
    // until generations pile up. scripts/sw-lint.py rejects that shape at commit time; this is
    // the runtime half of the contract.
    const mine = verNum(V);
    if (mine === null) return 0;

    const ks = await caches.keys();
    await Promise.all(ks
      .filter(k => { const n = verNum(k); return n !== null && n < mine; })
      .map(k => caches.delete(k)));
  } catch {
    // Storage went away mid-collect. Keep the old cache and retry on the next ping rather than
    // rejecting: this runs inside install's and the message handler's waitUntil().
    return SHELL.length;
  }
  return 0;
}

self.addEventListener("activate", e => {
  e.waitUntil(topUpThenCollect().then(() => self.clients.claim()));
});

// app.js pings this on every online load, foreground, and controllerchange, so an evicted
// precache heals on the next launch with a connection instead of waiting for the next V bump —
// and a collect deferred at activate time (incomplete shell, or an install in flight) gets
// retried here.
//
// NB: the collect deliberately lives in topUpThenCollect() and not inside ensureShellOnce(),
// which also runs during install — deleting the old cache then would strand pages still
// controlled by the previous worker.
self.addEventListener("message", e => {
  if (e.data === "ensure-shell") e.waitUntil(topUpThenCollect());
});

// Cache-write gate. A fetch() only REJECTS on a network failure — a 404 or a mid-deploy 502
// arrives as a RESOLVED response, so an ungated c.put() happily overwrites a good cached copy
// with an error body, which then survives as the offline fallback until the next V bump. (Same
// principle as data.js refusing to cache an empty 200: a 200-shaped response isn't necessarily a
// good one.)
//
// A redirected response can't be used to satisfy a navigation, so caching one is another route to
// a blank screen — if "./" ever grows a redirect, don't store it. 206 needs its own clause
// because resp.ok is TRUE for a partial (verified in both engines) and cache.put() then throws;
// irrelevant to JSON and icons, immediately relevant to any adopter caching audio or video.
//
// Opaque responses are the exception that must NOT be gated: a cross-origin no-cors fetch (a
// webfont, a CDN script) always reports ok:false and status:0 no matter how it went, so `resp.ok`
// alone would silently disable font caching and break offline type. They're allowed through
// explicitly — the cost is that a failed opaque request is indistinguishable from a good one.
// That's inherent to no-cors, not something the gate can fix. The Google Fonts branch below is
// what makes this clause reachable here; a copy that deletes that branch can drop it.
function cachePut(req, resp) {
  // SHELL entries are owned by ensureShellOnce() and by nothing else. Letting opportunistic
  // request traffic write them too is what produced MIXED-GENERATION caches: V is whatever the
  // CURRENT worker declares, so a shell file whose bytes changed on the server got overwritten in
  // the current cache one file at a time while its neighbours kept their older entries — no V
  // bump needed, one redeployed file is enough. This skeleton's shell is two coupled sets
  // (index.html + styles.css + app.js + theme.js + data.js, and usage/index.html +
  // usage/crunch.js); a document from one deploy driving scripts from another is exactly the
  // confusing-bug class. Skipping SHELL here makes "a V bump is what refreshes them" literally
  // true: each generation's shell is fetched once, together, by the install that created it.
  if (SHELL_HREFS.has(req.url)) return;
  if (resp.redirected || resp.status === 206) return;
  if (!resp.ok && resp.type !== "opaque") return;
  const copy = resp.clone();
  // The .catch() matters: non-GET requests, 206s, and quota exhaustion all surface at put(), and
  // an uncaught rejection in a SW is just noise in a log nobody reads — the caller's response has
  // already been returned either way.
  caches.open(V).then(c => c.put(req, copy)).catch(() => {});
}

// Read the CURRENT version first, then fall back to the whole store.
//
// CacheStorage.match() scans caches in CREATION order, so a lingering old version outranks the
// current one — collecting promptly only closes that shadowing by timing. Scoping the first
// lookup to V closes it by construction: the old cache can still fill a gap (it's the net that
// makes a failed V bump survivable) but it can no longer outrank a complete current shell.
// If only one thing from this file propagates to a downstream copy, it should be this.
//
// NEVER REJECTS. This is called from inside the offline catch handler, the last stop before
// offlineFallback() — a throw there escapes as a rejected respondWith(), and WebKit paints the
// same blank white screen this file exists to prevent. A bare caches.match() can't throw, but
// caches.open(V) can (site data blocked in Safari, corrupt or evicted storage). Resolve undefined
// instead and let the caller reach the fallback.
async function cacheLookup(req) {
  try {
    const c = await caches.open(V);
    const hit = await c.match(req);
    if (hit) return hit;
  } catch {}
  try {
    return await caches.match(req);
  } catch {
    return undefined;
  }
}

// Subresources a cached document cannot BOOT without, per document. Per-file precaching means the
// cache can legitimately hold a document while a script it needs is still missing (one 500 during
// install), and the shell fallback below is navigation-only by design — so offline, the document
// is served, its script request gets an empty 504, and the page boots broken: a bare header, no
// content, no error, no hint. Serving the honest offline page instead is strictly better — it
// says what to do, and one online launch repairs the precache.
//
// List only what the DOCUMENT dies without, not everything it loads — gating on a nice-to-have
// replaces a working offline page with an error page. As shipped:
//   - the root page renders its placeholder markup with NO scripts at all, so its honest list is
//     EMPTY. The moment your paint() owns the content, ./theme.js, ./data.js and ./app.js all
//     become boot-critical (a missing theme.js throws in boot() before render() ever runs), as
//     does any vendored chart lib — list them here then.
//   - usage/ is the opposite: crunch.js builds the whole dashboard, so without it the page sticks
//     at "loading…" forever.
const BOOT_DEPS = {
  "": [], "index.html": [],
  "usage/": ["./usage/crunch.js"], "usage/index.html": ["./usage/crunch.js"],
};

// Request pathname → BOOT_DEPS key, relative to the SW scope (works at user.github.io/repo/).
const SCOPE_PATH = new URL("./", self.location).pathname;
function docKey(pathname) {
  return pathname.startsWith(SCOPE_PATH) ? pathname.slice(SCOPE_PATH.length) : pathname;
}

// Uses cacheLookup(), not a V-scoped read: a dep that only survives in the previous generation's
// cache will still be SERVED from there, so it counts as present. The gate has to model what the
// subresource request will actually get, or it fires on pages that would have booted fine.
async function bootable(pathname) {
  const deps = BOOT_DEPS[docKey(pathname)] || [];
  return (await Promise.all(deps.map(u => cacheLookup(u)))).every(Boolean);
}

self.addEventListener("fetch", e => {
  const u = new URL(e.request.url);

  // cache.put() rejects for anything but GET ("Request method is not GET"), and a form POST is
  // mode === "navigate" — so without this it walks straight into the live branch and cachePut().
  // The skeleton has no POSTs; an adopter's form, sendBeacon, or Apps Script write (§Analytics)
  // inevitably is one.
  if (e.request.method !== "GET") return;

  // Google Fonts (if used): cache-first so the type survives offline. Offline with an UNCACHED
  // font this rejects rather than resolving undefined — a failed stylesheet request (type falls
  // back to system fonts), not a blank document, so it deliberately skips offlineFallback().
  if (u.hostname === "fonts.googleapis.com" || u.hostname === "fonts.gstatic.com") {
    e.respondWith(cacheLookup(e.request).then(r =>
      r || fetch(e.request).then(resp => { cachePut(e.request, resp); return resp; })));
    return;
  }

  // Cross-origin data (your APIs, third-party JSON): straight to network, don't touch the cache.
  if (u.origin !== location.origin) return;

  // The SW must never intercept or cache its own script: checkVer() probes
  // ./sw.js?_=<ts> to read the live version, and caching those probes both bloats
  // the cache (a new dead entry per resume) and — if .js is ever made cache-first
  // with ignoreSearch — serves a stale version back, wedging the "tap to update" tag.
  if (u.pathname.endsWith("/sw.js")) return;

  // Navigations are decided FIRST, ahead of the .json test below: a document request must always
  // end at a real page — including a direct navigation to a .json URL, which the SWR branch would
  // otherwise answer offline with a rejected respondWith (a bare network error), not the fallback.
  const live = e.request.mode === "navigate" || u.pathname.endsWith("/") || /\.(html|js)$/.test(u.pathname);

  // Same-origin JSON → serve the cached copy IMMEDIATELY, refresh behind it. This is the SW twin
  // of data.js's cache-first paint. JSON here is DATA (a committed dataset, the manifest), and
  // network-first made every cold start block on a round trip for it even with a perfectly good
  // cached copy. The tradeoff is real but small: a JSON change lands one load later than an
  // HTML/JS change. If some .json of yours is genuinely code-like and must be live, move it into
  // the `live` test above.
  if (!live && /\.json$/.test(u.pathname)) {
    e.respondWith(cacheLookup(e.request).then(cached => {
      // PRECACHED json is NOT revalidated: cachePut() refuses to write SHELL urls (they're
      // ensureShellOnce()'s to own), so revalidating one would fetch the payload and discard it —
      // cellular spent for nothing on every launch. A V bump is what refreshes it, which THE ONE
      // RULE already requires. Conditional on a cached copy EXISTING, so a first run or an
      // evicted entry still falls through to the network.
      if (cached && SHELL_HREFS.has(e.request.url)) return cached;
      const net = fetch(e.request).then(resp => { cachePut(e.request, resp); return resp; });
      e.waitUntil(net.catch(() => {}));   // keep the SW alive for the refresh; offline is fine
      // No cached copy (first run) → wait for the network, but END AT A RESPONSE: a first run
      // offline was the one branch left that could settle respondWith() with a rejection.
      return cached || net.catch(() => offlineFallback(e.request));
    }));
    return;
  }

  // Same-origin: HTML/JS + navigations → network-first; other assets (images) → cache-first.
  if (live) {
    e.respondWith(
      fetch(e.request).then(resp => {
        cachePut(e.request, resp);
        // A 4xx/5xx is a resolved fetch, so .catch() below never sees it — serve
        // the good cached copy instead of handing the app an error page.
        if (!resp.ok) return cacheLookup(e.request).then(r => r || resp);
        return resp;
      }).catch(async () => {
        // Offline. Try the exact request, then the shell, then give up VISIBLY. Resolving
        // respondWith() to undefined is the original blank-screen bug: WebKit fails the
        // navigation with "Returned response is null" and iOS paints a blank white page — no
        // text, no error, nothing to act on. Chromium survives it, which is why it never shows
        // up in desktop testing.
        //
        // A document we can't actually boot is worse than the honest fallback, so bootable() is
        // checked BEFORE the cached copy is handed back — including the exact-request hit below,
        // which for a navigation IS the document.
        if (e.request.mode === "navigate" && !(await bootable(u.pathname))) {
          return offlineFallback(e.request);
        }
        // The ./index.html fallback is doubly gated:
        //   - NAVIGATIONS only: `live` also matches .js, and handing HTML to an uncached
        //     theme.js request makes the script fail to PARSE instead of failing cleanly.
        //   - the ROOT document only: this is a multi-page skeleton, and answering an uncached
        //     /usage/ navigation with the root page hands the user the wrong document — the
        //     honest offline page beats a page they didn't ask for. What the root fallback still
        //     catches: query-variant navigations like "./?data=…", which miss the exact-match
        //     lookup above.
        const key = docKey(u.pathname);
        const shell = e.request.mode === "navigate" && (key === "" || key === "index.html")
          ? await cacheLookup("./index.html") : null;
        return (await cacheLookup(e.request)) || shell || offlineFallback(e.request);
      })
    );
  } else {
    e.respondWith(
      cacheLookup(e.request).then(r => r || fetch(e.request).then(resp => {
        cachePut(e.request, resp);
        return resp;
      }).catch(() => offlineFallback(e.request)))
    );
  }
});

// Terminal fallback: always a real Response, never undefined. Navigations get a readable page
// (the precache is empty or unbootable — the one thing that fixes it is one online launch, which
// ensureShell() then uses to repair itself); subresources get a plain 504.
//
// This page is a deliberate exception to two repo rules, so a copier doesn't "fix" it:
//   - CSS is INLINE, not in styles.css. It exists precisely for the case where the precache is
//     empty, so styles.css is by definition unavailable — a <link> would render it unstyled in
//     the one situation it's for. (Same reasoning as index.html's pre-paint theme stamp.)
//   - It HARDCODES the placeholder palette (#f5f5f5 / #1a1a1a / #2196f3) and system-ui — a
//     fallback page that depends on a cached font defeats itself. When rebranding, this is an
//     instance of the palette row in CLAUDE.md §Workflow step 2's replacement table.
function offlineFallback(req) {
  if (req.mode !== "navigate") {
    return new Response("", { status: 504, statusText: "Offline" });
  }
  return new Response(
    `<!doctype html><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Offline — APP</title>
<style>
  body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;
       background:#f5f5f5;color:#222;font:16px/1.5 system-ui,-apple-system,sans-serif}
  main{max-width:22em;padding:2em;text-align:center}
  h1{font-size:1.15em;margin:0 0 .6em}
  p{margin:.6em 0;color:#555}
  button{margin-top:1.2em;border:0;border-radius:999px;padding:.7em 1.3em;
         background:#2196f3;color:#fff;font-size:1em;cursor:pointer}
  @media (prefers-color-scheme:dark){ body{background:#1a1a1a;color:#eee} p{color:#aaa} }
</style>
<main>
  <h1>Offline, and nothing cached yet</h1>
  <p>The offline copy of this app hasn't been stored on this device — or the system reclaimed it
     to free up space.</p>
  <p>Open it once with a connection and it will rebuild itself for offline use.</p>
  <button onclick="location.reload()">Try again</button>
</main>`,
    { status: 503, headers: { "Content-Type": "text/html; charset=utf-8" } }
  );
}
